definitions:
  controller.Creds:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.BlockModel:
    properties:
      bucketName:
        type: string
      createTime:
        type: string
      hot:
        type: integer
      id:
        type: integer
      introduction:
        type: string
      isRecommend:
        type: boolean
      isShow:
        type: boolean
      modelFile:
        type: string
      modelType:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      totalCount:
        type: integer
      updateTime:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/blockModel:
    get:
      description: 这个接口返回分页的 BlockModel 列表
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.BlockModel'
            type: array
      summary: 分页返回 BlockModel 数据
      tags:
      - Block
  /v1/login:
    post:
      consumes:
      - application/json
      description: 通过用户名和密码进行登录，并返回 JWT Token
      parameters:
      - description: 用户登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Creds'
      produces:
      - application/json
      responses:
        "200":
          description: 返回 Token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 用户不存在
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - User
swagger: "2.0"
